### PR TITLE
PCIe Generic commits

### PR DESCRIPTION
**Pull request by gauravks**
The pull request contains generic commits for PCIe design on Windows.

Tested on B&R APC2100

### CODE REVIEW

**Comment by gauravks** [comment]
I have updated the fix commits as per our discussion. Please have a look and let me know if i missed something.

I have created an additional commit 
[FIX] Additional rename commit for memmap-winpcie.c to memmap-winioctl.c
for renaming the memmap-winpice.c to avoid conflicts during the squashing.

Please let me know if you face any issues while squashing the commits.

**Comment by zelenkaj** [comment]
I'm facing conflicts and therefore I would suggest closing this pull request and you share the commits step-by-step in new **pull requests** as Josef suggested!

**Comment by gauravks** [comment]
So, If I understand is correctly,I will create separate pull request with each having two commit, one the original commit and the fix commit right?

The commits in the pull request are interdependent and I will be able to create the request one by one only in this case which I think will take time to complete :(

Shall I prepare the squashed commits and share with you in a separate pull request?

**Comment by zelenkaj** [comment]
You can already share the squashed commits (so original + "[FIX] Incorporated..")

e.g. commit "[TASK] Add support for Windows kernel in stack" can be in a separated pull request like "[FEATURE] Add NDIS driver project for Windows PCIe solution"
But the commit "[FIX] Additional rename commit for memmap-winpcie.c to memmap-winioctl.c" must be on top of "[TASK] Add kernel to user memory mapping for Windows PCIe design", thus they can be provided in same pull request.

**Comment by gauravks** [comment]
To be integrated using separate commits.

**Pull request closed without merging**
