### PR TITLE
PCIe commits

### PR DESCRIPTION
**Pull request by gauravks**
This is the first set of commits for PCIe branch.

The pull request includes:
1. Changes to support heterogenous processor architectures.
2. Modifications in dualprocshm library to support heterogenous systems.
3. Windowns PCIe support for dualprocshm library.
4. NDIS PCIe library.

The commits were tested on:
- APC2100 (Windows PCIe design)
- Xilinx Zynq ZC7020 (Dualprocshm design)

Additionally the commit "[TASK] Add support for heterogenous processor architectures" was tested on
- Linux ( Linux Kernel module)
- Windows (Link to application)

### CODE REVIEW

**Comment by zelenkaj** [comment]
A minor warning on Linux...

hrestimer-linuxkernel.c:448, GNU C Compiler 4 (gcc), Priorität: Normal
format ‘%lX’ expects argument of type ‘long unsigned int’, but argument 2 has type ‘tTimerHdl’ [-Wformat]

**Comment by zelenkaj** [comment]
On noos targets three warnings...

timer-generic.c:268, GNU C Compiler 4 (gcc), Priorität: Normal
cast from pointer to integer of different size

timer-generic.c:334, GNU C Compiler 4 (gcc), Priorität: Normal
cast from pointer to integer of different size

timer-generic.c:424, GNU C Compiler 4 (gcc), Priorität: Normal
cast to pointer from integer of different size

**Comment by gauravks** [comment]
The warnings are due to the use of UINT64 for `tTimerHdl`.

Again to fix the warnings we need union or `OPLK_PTR_T` approach with `tTimerHdl`.

**Comment by zelenkaj** [comment]
generally the tTimerHdl usage is very ugly :) but I guess using union is also here a way of avoiding warnings. what do you think?

**Comment by gauravks** [comment]
Yeah, it is better as it will be a common approach I will share the fix

**Comment by zelenkaj** [comment]
The changes are integrated into develop-pcie. Please look into and close the pull request if the branch is okay.

**Comment by zelenkaj** [comment]
Changes are integrated - please check and let me know if I can close the pull request!

**Comment by gauravks** [comment]
noticed a compilation issue on edrv i210. Have update the pull request. Sorry for the inconvenience.

**Comment by zelenkaj** [comment]
No issue, cherry-picking is not a big issue at all :)

**Comment by zelenkaj** [comment]
I sqashed the Fix i210 commit into "[TASK] Add support for heterogenous processor architectures" - please let me know if i can close that pull request

**Comment by gauravks** [comment]
Thanks. Please update the commit message for commit 4d7524a150703b0f5480d8cc97177f024a0cdfaf as following:

[TASK] Add support for heterogenous processor architectures

Update structures shared between user and kernel layers to
support heterogenous processor architectures such as
X86_64 system with 32 bit NIOS2 or Microblaze.

Include following changes:

- **Use union of pointer and 64 bit variable for the event
  argument variable and union of tTimerHdl and 64 bit
  variable in the tTimerEventArg structure.This will avoid
  the size mismatch between the processors.**
- Add additional padding variables to structures to avoid size
  mismatch due to different packing schemes on 32 bit and 64 bit
  systems.
- Reorder variables within structures to avoid unwanted padding
  by the compilers on 64 bit systems.

**Comment by zelenkaj** [comment]
done

**Comment by gauravks** [comment]
Thanks.

**Pull request closed without merging**
